name: CICD - DockerHub Build & Push

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: heartzbyeboo/byeboo

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar

      - name: DockerHub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx 설치 및 멀티 플랫폼 빌드
        run: |
          docker buildx create --use --name byeboo-builder || docker buildx use byeboo-builder
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=build/libs/byeboo.jar \
            -t $DOCKER_IMAGE:latest \
            --push .

  cd:
    needs: [ci]
    runs-on: ubuntu-latest

    steps:
      - name: SSH 접속 및 배포 & 헬스 체크
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/byeboo-deploy
            docker pull heartzbyeboo/byeboo:latest
            chmod +x ./deploy.sh
            ./deploy.sh

      - name: 배포 실패 여부 확인
        if: failure()
        run: |
          echo "❌ 배포 실패: 헬스 체크 통과하지 못했습니다."
          exit 1

      - name: 배포 성공 확인
        if: success()
        run: |
          echo "✅ 배포 성공 및 트래픽 전환 완료"